google_survey_example/config/routes.rb
Rails.application.routes.draw do
  get 'user/index'

  get 'welcome_gates/index'
  get 'walls/timeline', to: "walls#timeline"
  get 'walls/survey', to: "walls#survey"
  get 'walls/answer_list', to: "walls#answer_list"
  get 'walls/question_list', to: "walls#question_list"
  resources :walls do
    resources :comments
  end

resources :users
resources :answer_shorts

resources :questions

  root 'welcome_gates#index'

end

google_survey_example/app/models/answer_long.rb
class AnswerLong < ActiveRecord::Base
  belongs_to :user_id
  belongs_to :question_id
end

google_survey_example/app/models/answer_short.rb
class AnswerShort < ActiveRecord::Base
  belongs_to :user_id
  belongs_to :question_id
end

google_survey_example/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :wall
end

google_survey_example/app/models/question.rb
class Question < ActiveRecord::Base
end

google_survey_example/app/models/user.rb
class User < ActiveRecord::Base
end

google_survey_example/app/models/wall.rb
class Wall < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
                    length: { minimum: 5 }      
end

google_survey_example/app/controllers/answer_shorts_controller.rb
class AnswerShortsController < ApplicationController
	
	def new
		# @answer_short = AnswerShort.new
	end
# 
	# def new_programming
	# 	@answer_short = AnswerShort.new
	# 	render "answer_shorts/new_programming"
	# end

	# def new_design
	# 	@answer_short = AnswerShort.new
	# end

	# def new_economics
	# 	@answer_short = AnswerShort.new
	# end

	# def create_programming
	# end


	def create
		@answer_short = AnswerShort.new(answer_short_params)
		
		@answer_short.save
		redirect_to @answer_short
	end

	def edit
		@answer_short = AnswerShort.find(params[:id])
	end

	def update
		@answer_short = AnswerShort.find(params[:id])

		if @answer_short.update(answer_short_params)
			redirect_to @answer_short
		else
			render 'edit'
		end
	end

	def create
		 @answer_short = AnswerShort.new(answer_short_params)
		  @answer_short.save
		  redirect_to @answer_short
	end

	def show
		@answer_short = AnswerShort.find(params[:id])
	end

	def index
		@answer_shorts = AnswerShort.all
	end

	def destroy
		@answer_short = AnswerShort.find(params[:id])
		@answer_short.destroy

		redirect_to answer_shorts_path
	end

	private
		  def answer_short_params
		    params.require(:answer_short).permit(:answer, :public_result)
		  end
	
end

google_survey_example/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

google_survey_example/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@wall = Wall.find(params[:wall_id])
		@comment = @wall.comments.create(comment_params)
		redirect_to wall_path(@wall)
	end
	def destroy
		@wall = Wall.find(params[:wall_id])
		@comment = @wall.comments.find(params[:id])
		@comment.destroy
		redirect_to wall_path(@wall)
	end

	private 
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end

end

google_survey_example/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def new
	end

	def create
		@question = Question.new(question_params)
		
		@question.save
		redirect_to @question
	end

	def edit
		@question = Question.find(params[:id])
	end

	def update
		@question = Question.find(params[:id])

		if @question.update(question_params)
			redirect_to @question
		else
			render 'edit'
		end
	end

	def show
		@question = Question.find(params[:id])
	end

	def index
		@questions = Question.all
	end

	def destroy
		@question = Question.find(params[:id])
		@question.destroy

		redirect_to questions_path
	end

	private
	def question_params
		params.require(:question).permit(:content, :selection_option, :skill_area)
	end
end

google_survey_example/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
	end

	def create
		@user = User.new(user_params)
		
		@user.save
		redirect_to @user
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)
			redirect_to @user
		else
			render 'edit'
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def index
		@users = User.all
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy

		redirect_to users_path
	end

	private
	def user_params
		params.require(:user).permit(:name, :nickname, :password)
	end
end

google_survey_example/app/controllers/walls_controller.rb
class WallsController < ApplicationController
	#before_action : set_wall, only: [:show, :edit, :destroy]
	#before_action : check_authority
	# after_action : set_wall, except
	def show
		
	end

	def new
	end

	def index
		@answer_shorts = AnswerShort.all
		@questions = Question.all
		@walls = Wall.all
	end

	def create
	#	render plain: params[:wall].inspect
	#	render Wall.new(wall_params).inspect
		@question = Question.new(params.require(:question).permit(:content, :selection_option, :skill_area))

		@question.save
		redirect_to walls_answer_list_path

	end
	def edit
	end
	def update
		 @wall = Wall.find(params[:id])
 
		  if @wall.update(wall_params)
		    redirect_to @wall
		  else
		    render 'edit'
		  end

	end
	def destroy
		@wall.destroy
		redirect_to walls_path
	end

	
	def timeline
		@walls = Wall.all
	end

	def survey
		@answer_shorts = AnswerShort.all
		@questions = Question.all
		@walls = Wall.all
	end

	def answer_list
		@answer_shorts = AnswerShort.all
		@walls = Wall.all
	end
	def question_list
		@questions = Question.all
		@walls = Wall.all
	end


	private
		def wall_params
			params.require(:wall).permit(:title, :text,:user_id,:read_authority)
		end
	private
		def set_wall
			@wall = Wall.find(params[:id]) 
		end
end

google_survey_example/app/controllers/welcome_gates_controller.rb
class WelcomeGatesController < ApplicationController
  def index
  end
end

google_survey_example/app/helpers/answer_shorts_helper.rb
module AnswerShortsHelper
end

google_survey_example/app/helpers/application_helper.rb
module ApplicationHelper
end

google_survey_example/app/helpers/comments_helper.rb
module CommentsHelper
end

google_survey_example/app/helpers/questions_helper.rb
module QuestionsHelper
end

google_survey_example/app/helpers/users_helper.rb
module UsersHelper
end

google_survey_example/app/helpers/walls_helper.rb
module WallsHelper
end

google_survey_example/app/helpers/welcome_gates_helper.rb
module WelcomeGatesHelper
end

google_survey_example/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
 <%= link_to 'Destroy Comment', [comment.wall, comment],
			 method: :delete,
			 data: { confirm: 'Are you sure?' } %>			
</p>

google_survey_example/app/views/comments/_form.html.erb
<%= form_for([@wall, @wall.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit "+", class: "glyphicon glyphicon-arrow-left btn btn-lg btn-default" %>
  </p>
<% end %>

google_survey_example/app/views/users/edit.html.erb
<h1>Editing user</h1>


<%= form_for :user, url: user_path(@user), method: :patch do |f| %>
 
<p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %>
  </p>

  <p>
     <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

<p>
<%= f.submit %>
</p>

<% end %>

<%= link_to 'Back', users_path %>

google_survey_example/app/views/users/index.html.erb
<ol class="breadcrumb">
  <li class="active">Qiestion list</li><!-- question/index -->
  <li><a href="/users">User list</a></li><!-- user/index -->
  <li><a href="/answers_short">Answer short list</a></li> <!-- answer/index -->
  <li><a href="/answers_long">Answer long list</a></li> <!-- answer/index -->
</ol>


<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">questions details</div>
  <div class="panel-body">

<table class="table">
  <tr>
    <th>user_id</th>
    <th>Name</th>
    <th>Nickname</th>
    <th>password</th>
    <th> </th>
    <th></th>
    <th></th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td ><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.nickname %></td>
      <td><%= user.password %></td>
       <td><%= link_to '', user_path(user), class: "glyphicon glyphicon-zoom-in btn-default" %></td>
      <td><%= link_to '', edit_user_path(user) , class: "glyphicon glyphicon-wrench btn-default" %></td>
      <td><%= link_to '', user, 
                      method: :delete, data: {confirm: 'Are you sure?' }, class: "glyphicon glyphicon-trash btn-default" %></td>
    
    </tr>
  <% end %>
</table>
<nav>
 
</nav>
</div>
</div>
 <%= link_to '', new_user_path, class: "glyphicon glyphicon-plus btn btn-default floating_btn" %>

google_survey_example/app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %>
  </p>
 
   <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
   </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', users_path %>

google_survey_example/app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
 
 <p>
  <strong>Nickname:</strong>
  <%= @user.nickname %>
</p>

 <p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>


<%= link_to '', users_path,class: " glyphicon glyphicon-th-list btn default_btn" %> 
<%= link_to '', edit_user_path,class: " glyphicon glyphicon-wrench btn btn-default" %> 
<%= link_to '', @user,
                      method: :delete, data: {confirm: 'Are you sure?' }, class: "glyphicon glyphicon-trash btn default_btn" %>

google_survey_example/app/views/walls/answer_list.html.erb
<ol class="breadcrumb">
    <li><a href="/walls">My list</a></li>
    <li><a href="/walls/question_list">Question List</a></li> 
	<li class="active">Answer list</a></li>
	<li><a href="/walls/survey">Survey</a></li> 
</ol>

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">answer_short details</div>
  <div class="panel-body">

<table class="table">
  <tr>
    <th>answer_short_id</th>
    <th>answer</th>
    <th>public_result</th>
    <th>user_id</th>
    <th>question_id</th>
    <th> </th>
    <th></th>
    <th></th>
  </tr>

  <% @answer_shorts.each do |answer_short| %>
    <tr>
      <td ><%=answer_short.id %></td>
      <td><%= answer_short.answer %></td>
      <td><%= answer_short.public_result %></td>
      <td><%= answer_short.user_id %></td>
      <td><%= answer_short.question_id %></td>
       <td><%= link_to '', answer_short_path(answer_short), class: "glyphicon glyphicon-zoom-in btn-default" %></td>
      <td><%= link_to '', edit_answer_short_path(answer_short) , class: "glyphicon glyphicon-wrench btn-default" %></td>
      <td><%= link_to '', answer_short, 
                      method: :delete, data: {confirm: 'Are you sure?' }, class: "glyphicon glyphicon-trash btn-default" %></td>

    </tr>
  <% end %>
</table>
<nav>
 
</nav>
</div>
</div>
  <%= link_to '', new_answer_short_path, class: "glyphicon glyphicon-plus btn btn-default floating_btn" %>

google_survey_example/app/views/walls/edit.html.erb
<h1>this is editing wall</h1>

    <%= form_for :wall, url: wall_path(@wall), method: :patch do |f| %>
  <% if @wall.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@wall.errors.count, "error") %> prohibited
      this wall from being saved:</h2>
    <ul>
    <% @wall.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

	<p>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
	</p>

	<p>
	<%= f.label :text %><br>
    <%= f.text_area :text %>
 	</p>


 	<% f.label :user_id %><br>
    <%= f.hidden_field :user_id , value: 0 %>

    <% f.label :read_authority %><br>
     <%= f.text_area :read_authority %>
<!--
 	<p>
	<%= f.label :user_id %><br>
    <%= f.text_area :user_id %>
 	</p>

 	<p>
	<%= f.label :read_authority %><br>
    <%= f.text_area :read_authority %>
 	</p>
-->


 	  <p>
    <%= f.submit %>  <%= link_to '', walls_path, class: "glyphicon glyphicon-remove btn btn-default" %> 

  </p>
<% end %>

google_survey_example/app/views/walls/index.html.erb
<ol class="breadcrumb">
  <li class="active">My list</li>
  <li><a href="/walls/question_list">Question LIst</a></li>
  <li><a href="/walls/answer_list">Answer list</a></li> 
   <li><a href="/walls/survey">Survey</a></li> 

</ol>

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Notes on my wall</div>
  <div class="panel-body">

<table class="table">
  <tr>
    <th>question_id</th>
    <th>content</th>
    <th>seletion_option</th>
    <th>skill_area</th>
  </tr>

  <% @questions.each do |question| %>
  <% display_count =0%>
    <% @answer_shorts.each do |answer_short| %>

    <% if answer_short.public_result ==  0 && display_count == 0 %>
      <% display_count =1%>
       <tr>
        <td ><%= question.id %></td>
        <td><%= question.content %></td>
        <td>답변내용 <%= answer_short.answer %></td>
        <td>공유 정도 <%= answer_short.public_result %></td>      
       </tr>

    <% end %>  <!-- if_answer_s -->
  <% end %> <!--  answer_shorts.each answer_short  -->

  <% if display_count == 0 %>
        <tr>
        <td ><%= question.id %></td>
        <td><%= question.content %></td>
        <td>x</td>
        <td>x</td>
        </tr>
  <%end%> <!-- if_display_count -->

  <% end %> <!--  questions.each question  -->
 
</table>

</div>
</div>

google_survey_example/app/views/walls/new.html.erb
<%= form_for :wall, url: walls_path do |f| %>

	<h1>this is new note</h1>
	<p>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
	</p>

	<p>
	<%= f.label :text %><br>
    <%= f.text_area :text %>
 	</p>


 	<% f.label :user_id %><br>
    <%= f.hidden_field :user_id , value: 0 %>

    <% f.label :read_authority %><br>
    <%= f.hidden_field :read_authority , value: 0 %>
<!--
 	<p>
	<%= f.label :user_id %><br>
    <%= f.text_area :user_id %>
 	</p>

 	<p>
	<%= f.label :read_authority %><br>
    <%= f.text_area :read_authority %>
 	</p>
-->


 	  <p>
    <%#= f.submit "", class: "btn btn-primary btn-lg" %>
    <%= button_tag :submit, class: "" do %>
        <%= content_tag :span, "", class: "glyphicon glyphicon-ok btn btn-default" %>
    <% end %> 

    <%= link_to '', walls_path, class: "glyphicon glyphicon-remove btn btn-default" %> 
    <%= link_to '',  walls_path,class: "glyphicon glyphicon-ok btn btn-default" %> 
   <%= f.submit '', :class => "my_sbtn my_sbtn2"  %>

  </p>
<% end %>

google_survey_example/app/views/walls/new_survey.html.erb
<%= form_for :wall, url: walls_path do |f| %>

	<h1>survey for SSD peer mathing</h1>

    <% @questions.each do |question| %>
        
  <p>
       <%=  question.content %><br>
    <%= f.text_field :content %>
  </p>
 
  <p>
    <%= question.selection_option %><br>
    <%= f.text_area :selection_option %>
  </p>

  <p>
     <%= f.label :skill_area %><br>
    <%= f.hidden_field :skill_area , value: question.id %>
  </p>

 	  <p>
    <%#= f.submit "", class: "btn btn-primary btn-lg" %>
    <%= button_tag :submit, class: "" do %>
        <%= content_tag :span, "", class: "glyphicon glyphicon-ok btn btn-default" %>
    <% end %> 

    <%= link_to '', walls_path, class: "glyphicon glyphicon-remove btn btn-default" %> 
    <%= link_to '',  walls_path,class: "glyphicon glyphicon-ok btn btn-default" %> 
   <%= f.submit '', :class => "my_sbtn my_sbtn2"  %>

  </p>
<% end %>



<!-- 
  <% @questions.each do |question| %>
    <tr>
      <td ><%= question.id %></td>
      <td><%= question.content %></td>
      <td><%= question.selection_option %></td>
      <td><%= question.skill_area %></td>
    
    </tr>
  <% end %> -->

google_survey_example/app/views/walls/question_list.html.erb
<ol class="breadcrumb">
    <li><a href="/walls">My list</a></li>
    <li class="active">Question List</a></li> 
    <li><a href="/walls/answer_list">Answer list</a></li> 
<li><a href="/walls/survey">Survey</a></li> 
</ol>



<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Notes on my wall</div>
  <div class="panel-body">

<table class="table">
  <tr>
    <th>question_id</th>
    <th>content</th>
    <th>seletion_option</th>
    <th>skill_area</th>
  </tr>
 
  <% @questions.each do |question| %>
    <tr>
      <td ><%= question.id %></td>
      <td><%= question.content %></td>
      <td><%= question.selection_option %></td>
      <td><%= question.skill_area %></td>
    
    </tr>
  <% end %>
</table>
<nav>
  <ul class="pager">
    <li><%= link_to '', walls_path, class: "glyphicon glyphicon-arrow-left btn btn-default" %>  </li>
    <li><%= link_to '', new_wall_path, class: "glyphicon glyphicon-plus btn btn-default" %></li>
    </ul>
</nav>

google_survey_example/app/views/walls/show.html.erb
<p>
<strong>Title:</strong>
<%= @wall.title %>
</p>

<p>
<strong>Text:</strong>
<%= @wall.text %>
</p>

<p>
<strong>User_id:</strong>
<%= @wall.user_id %>
</p>

<p>
<strong>Read_authority:</strong>
<%= @wall.read_authority %>
</p>

<h2>comments</h2>
<%= render @wall.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to '', walls_path,class: " glyphicon glyphicon-th-list btn default_btn" %> 
<%= link_to '', new_wall_path,class: " glyphicon glyphicon-pencil btn default_btn" %> 
<%= link_to '', @wall,
                      method: :delete, data: {confirm: 'Are you sure?' }, class: "glyphicon glyphicon-trash btn default_btn" %>

google_survey_example/app/views/walls/survey.html.erb
<ol class="breadcrumb">
    <li><a href="/walls">My list</a></li>
    <li><a href="/walls/question_list">Question List</a></li> 
    <li><a href="/walls/answer_list">Answer list</a></li> 
    <li  class="active">Survey</a></li> 
</ol>



<%= form_for :wall, url: walls_path do |f| %>

    <h1>survey for SSD peer matching</h1>

        <% @questions.each do |question| %>
            <p>
             <%=  question.content %><br>
             <%= f.text_field :content %>
            </p>

            <p>
                <%= question.selection_option %><br>
                <%= f.text_area :selection_option %>
            </p>

            <p>
               <%= f.label :skill_area %><br>
               <%= f.hidden_field :skill_area , value: question.id %>
            </p>

            <p>
                <%#= f.submit "", class: "btn btn-primary btn-lg" %>
                <%= button_tag :submit, class: "" do %>
                <%= content_tag :span, "", class: "glyphicon glyphicon-ok btn btn-default" %>
        <% end %> 
        <% end %>
            <%= link_to '', walls_path, class: "glyphicon glyphicon-remove btn btn-default" %> 
            <%= link_to '',  walls_path,class: "glyphicon glyphicon-ok btn btn-default" %> 
            <%= f.submit '', :class => "my_sbtn my_sbtn2"  %>

        </p>
<% end %>

google_survey_example/app/views/walls/timeline.html.erb
<ol class="breadcrumb">
	<li><a href="/walls">My wall</a></li>
	<li class="active">Timeline</a></li>
	<li><a href="#">Friends List</a></li> 
</ol>


<div class="panel panel-primary">
	<!-- Default panel contents -->
	<div class="panel-heading">Notes on my wall</div>
	<div class="panel-body">

		<% @walls.each do |wall| %>

		<% if wall.read_authority == 0  %> 

		<div class="panel  panel-info">
			<div class="panel-heading">
				<h3 class="panel-title"><%= wall.title %></h3>
			</div>

			<div class="panel-body panel-body_custom">
				<%= wall.text %> 
			</div>
			
			<div class="panel-body panel-body_custom">
				read_authority [  <%= wall.read_authority %>  ]
			</div>

			<div class="panel-body panel-body_custom">
				<table class="table">
					<td><%= link_to '', wall_path(wall), class: "glyphicon glyphicon-zoom-in btn-default" %></td>
					<td><%= link_to '', edit_wall_path(wall) , class: "glyphicon glyphicon-wrench btn-default" %></td>
					<td><%= link_to '', wall, 
						method: :delete, data: {confirm: 'Are you sure?' }, class: "glyphicon glyphicon-trash btn-default" %></td>
					</table>
				</div>
			</div>

			<% end %> 


			<% end %>



			<nav>
				<ul class="pager">
					<li><%= link_to '', walls_path, class: "glyphicon glyphicon-arrow-left btn btn-default" %>  </li>
					<li><%= link_to '', new_wall_path, class: "glyphicon glyphicon-plus btn btn-default" %></li>
				</ul>
			</nav>

		</div>
	</div>
</div>
</div>

google_survey_example/app/views/welcome_gates/index.html.erb
<div class="jumbotron">
  <h1>HUMAGNET, world!</h1>
  <p>if you want to start human's networld click 'Learn more'</p>
  <p><a class="btn btn-primary btn-lg" href="/questions" role="button">Learn more</a></p>
</div>